N = input()
#A = map(int, raw_input().split())
A = raw_input().split()
A = ''.join(A)
print int(A) % (10**9+7) N = input()
#A = map(int, raw_input().split())
A = raw_input().split()
A = ''.join(A)
print int(A) % (10**9+7)
